version: '3.3'

services:
  registry:
    image: eureka-server
    container_name: eureka-server
    build: eureka-server
    ports:
      - 8761:8761
  user-service:
    image: user-service
    container_name: user-service
    build: user-service
    ports:
      - 8081:8081
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build: authentication-service
    ports:
      - 8082:8082
  expert-service:
    image: expert-service
    container_name: expert-service
    build: expert-service
    ports:
      - 8083:8083
  customer-service:
    image: customer-service
    container_name: customer-service
    build: customer-service
    ports:
      - 8084:8084
  payment-service:
    image: payment-service
    container_name: payment-service
    build: payment-service
    ports:
      - 8085:8085
  email-service:
    image: email-service
    container_name: email-service
    build: email-service
    ports:
      - 8086:8086
  feedback-service:
    image: feedback-service
    container_name: feedback-service
    build: feedback-service
    ports:
      - 8087:8087
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build: api-gateway
    ports:
      - 8080:8080

  mongodb:
    image: 'mongo:6.0.3'
    container_name: mongodb
    ports:
      - 27017:27017
  mysqldb:
    image: 'mysql:8.0'
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=doorstep
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=doorstep
  rabbitmq:
    image: 'rabbitmq:3.9-management'
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672